name: Push To GCS Bucket

on:
  workflow_call:
    secrets:
      GCP_SA_EMAIL:
        description: 'Service Account Email'
        required: true
      GCP_SA_KEY:
        description: 'Service Account Key'
        required: true
      GCS_BUCKET:
        description: 'Bucket to publish too'
        required: true

jobs:
  push:
    name: 'Deploy to GCS'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Authenticate on GCS
        uses: google-github-actions/auth@v0
        with:
          service_account: '${{ secrets.GCP_SA_EMAIL }}'
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - run: gsutil -m rsync -d -c -r public gs:// '${{ secrets.GCS_BUCKET }}'
